import { SCHEMA_VERSION, type Database } from '@/lib/schema'
import {
  applyStatusToChecklist,
  LEAD_STAGE_ORDER,
  LEAD_STAGE_PROBABILITY,
} from '@/lib/constants'
import {
  ActivityAction,
  CalendarEventType,
  ClientStatus,
  ContractFrequency,
  ContractStatus,
  ExpenseCategory,
  LeadSource,
  LeadStage,
  PaymentMethod,
  PaymentStatus,
  Priority,
  ProjectStatus,
  RevisionStatus,
  TaskStatus,
  VideoStatus,
  VideoType,
  type ActivityLog,
  type CalendarEvent,
  type Client,
  type Contract,
  type Expense,
  type FileLink,
  type Lead,
  type LeadActivity,
  type Payment,
  type Project,
  type Task,
  type Video,
  type VideoChecklist,
  type VideoChecklistKey,
  type VideoRevision,
} from '@/types'

/**
 * Dados demonstrativos do FrameFlow.
 *
 * Os ids são fixos e legíveis (`c1`, `p3`, `v15`) porque são as mesmas
 * referências usadas na documentação de arquitetura — dá para conferir os
 * totais por cliente à mão. Registros criados pela aplicação usam ids gerados.
 *
 * O conjunto retrata um editor no fim de agosto de 2026 com atrasos reais:
 * há vídeos e cobranças vencidos de propósito, para que alertas, badges de
 * atraso e o painel de prazos tenham o que mostrar.
 */

/** Data de referência do cenário. */
const TODAY = '2026-08-26'

/** Converte `YYYY-MM-DD` em instante ISO — usado em createdAt/updatedAt. */
function at(day: string, hour = 9): string {
  return `${day}T${String(hour).padStart(2, '0')}:00:00.000Z`
}

/* -------------------------------------------------------------------------- */
/*                                  Clientes                                  */
/* -------------------------------------------------------------------------- */

const clients: Client[] = [
  {
    id: 'c1',
    name: 'João Silva',
    company: null,
    email: 'joao.silva@email.com',
    phone: '(11) 98812-4477',
    whatsapp: '5511988124477',
    instagram: '@joaosilva.financas',
    youtube: 'youtube.com/@joaosilvafinancas',
    website: null,
    niche: 'Finanças pessoais',
    status: ClientStatus.ACTIVE,
    source: LeadSource.INSTAGRAM,
    leadId: null,
    entryDate: '2025-09-15',
    notes: 'Publica toda segunda e quinta. Prefere receber o corte final até 48h antes.',
    createdAt: at('2025-09-15'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'c2',
    name: 'Maria Santos',
    company: 'Maria Studio',
    email: 'contato@mariastudio.com.br',
    phone: '(21) 99654-1120',
    whatsapp: '5521996541120',
    instagram: '@mariastudio',
    youtube: null,
    website: 'mariastudio.com.br',
    niche: 'Beleza / Estética',
    status: ClientStatus.ACTIVE,
    source: LeadSource.REFERRAL,
    leadId: null,
    entryDate: '2025-11-01',
    notes: 'Pacote mensal de 6 reels. Envia o material bruto pelo Drive na primeira semana.',
    createdAt: at('2025-11-01'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'c3',
    name: 'Pedro Costa',
    company: 'TechVida',
    email: 'pedro@techvida.io',
    phone: '(31) 98123-9080',
    whatsapp: '5531981239080',
    instagram: '@techvida',
    youtube: 'youtube.com/@techvida',
    website: 'techvida.io',
    niche: 'Tecnologia',
    status: ClientStatus.ACTIVE,
    source: LeadSource.YOUTUBE,
    leadId: null,
    entryDate: '2026-01-10',
    notes: 'Aprova em duas rodadas. Exige color grading conferido antes do envio.',
    createdAt: at('2026-01-10'),
    updatedAt: at('2026-08-05'),
  },
  {
    id: 'c4',
    name: 'Lucas Almeida',
    company: null,
    email: 'lucas.almeida@email.com',
    phone: '(41) 99201-3344',
    whatsapp: '5541992013344',
    instagram: '@lucasalmeida.fit',
    youtube: null,
    website: null,
    niche: 'Fitness',
    status: ClientStatus.PAUSED,
    source: LeadSource.COLD_EMAIL,
    leadId: null,
    entryDate: '2025-07-20',
    notes: 'Pausou em junho. Fatura de maio segue em aberto — cobrança pendente.',
    createdAt: at('2025-07-20'),
    updatedAt: at('2026-06-05'),
  },
  {
    id: 'c5',
    name: 'Agência Norte',
    company: 'Agência Norte',
    email: 'producao@agencianorte.com',
    phone: '(51) 3025-8890',
    whatsapp: '555130258890',
    instagram: '@agencianorte',
    youtube: null,
    website: 'agencianorte.com',
    niche: 'Marketing',
    status: ClientStatus.ACTIVE,
    source: LeadSource.NETWORKING,
    leadId: null,
    entryDate: '2026-03-01',
    notes: 'Intermedia clientes finais. Briefings chegam por e-mail, sempre com deadline curto.',
    createdAt: at('2026-03-01'),
    updatedAt: at('2026-08-05'),
  },
]

/* -------------------------------------------------------------------------- */
/*                                  Projetos                                  */
/* -------------------------------------------------------------------------- */

const projects: Project[] = [
  {
    id: 'p1',
    name: 'Canal YouTube — Julho',
    clientId: 'c1',
    description: '8 vídeos: 6 longform semanais e 2 shorts de apoio.',
    type: 'YouTube',
    status: ProjectStatus.ACTIVE,
    startDate: '2026-07-01',
    deadline: '2026-07-31',
    contractedValue: 3200,
    estimatedCost: 200,
    responsible: 'Gabriel',
    notes: null,
    createdAt: at('2026-06-25'),
    updatedAt: at('2026-08-20'),
  },
  {
    id: 'p2',
    name: 'Reels Julho',
    clientId: 'c2',
    description: '6 reels de 30 a 60 segundos.',
    type: 'Instagram',
    status: ProjectStatus.ACTIVE,
    startDate: '2026-07-01',
    deadline: '2026-07-31',
    contractedValue: 2400,
    estimatedCost: 120,
    responsible: 'Gabriel',
    notes: null,
    createdAt: at('2026-06-27'),
    updatedAt: at('2026-08-18'),
  },
  {
    id: 'p3',
    name: 'Vídeo Institucional',
    clientId: 'c3',
    description: 'Peça institucional de 2 minutos com motion graphics.',
    type: 'Institucional',
    status: ProjectStatus.ACTIVE,
    startDate: '2026-07-15',
    deadline: '2026-08-15',
    contractedValue: 4500,
    estimatedCost: 700,
    responsible: 'Gabriel',
    notes: 'Motion graphics terceirizado. Trilha aprovada pelo cliente.',
    createdAt: at('2026-07-10'),
    updatedAt: at('2026-08-10'),
  },
  {
    id: 'p4',
    name: 'Reels Fitness',
    clientId: 'c4',
    description: 'Pacote mensal pausado a pedido do cliente.',
    type: 'Instagram',
    status: ProjectStatus.PAUSED,
    startDate: '2026-05-01',
    deadline: '2026-05-31',
    contractedValue: 1600,
    estimatedCost: 0,
    responsible: 'Gabriel',
    notes: 'Retomar apenas após quitação da fatura de maio.',
    createdAt: at('2026-04-25'),
    updatedAt: at('2026-06-05'),
  },
  {
    id: 'p5',
    name: 'Campanha Ads',
    clientId: 'c5',
    description: '5 peças de anúncio em três durações para teste A/B.',
    type: 'Anúncios',
    status: ProjectStatus.ACTIVE,
    startDate: '2026-08-01',
    deadline: '2026-08-31',
    contractedValue: 6000,
    estimatedCost: 400,
    responsible: 'Gabriel',
    notes: null,
    createdAt: at('2026-07-28'),
    updatedAt: at('2026-08-22'),
  },
  {
    id: 'p6',
    name: 'Canal YouTube — Agosto',
    clientId: 'c1',
    description: 'Continuação do pacote mensal. Briefings ainda não abertos.',
    type: 'YouTube',
    status: ProjectStatus.PLANNING,
    startDate: '2026-08-01',
    deadline: '2026-08-31',
    contractedValue: 3200,
    estimatedCost: 200,
    responsible: 'Gabriel',
    notes: null,
    createdAt: at('2026-07-26'),
    updatedAt: at('2026-07-26'),
  },
  {
    id: 'p7',
    name: 'Podcast — Série',
    clientId: 'c3',
    description: 'Dois episódios de podcast em vídeo, com cortes para redes.',
    type: 'Podcast',
    status: ProjectStatus.COMPLETED,
    startDate: '2026-04-01',
    deadline: '2026-06-30',
    contractedValue: 3000,
    estimatedCost: 0,
    responsible: 'Gabriel',
    notes: 'Entregue e pago integralmente.',
    createdAt: at('2026-03-25'),
    updatedAt: at('2026-06-20'),
  },
  {
    id: 'p8',
    name: 'Reels Agosto',
    clientId: 'c2',
    description: 'Pacote mensal de reels.',
    type: 'Instagram',
    status: ProjectStatus.ACTIVE,
    startDate: '2026-08-01',
    deadline: '2026-08-31',
    contractedValue: 2400,
    estimatedCost: 120,
    responsible: 'Gabriel',
    notes: null,
    createdAt: at('2026-07-28'),
    updatedAt: at('2026-08-20'),
  },
]

/* -------------------------------------------------------------------------- */
/*                                   Vídeos                                   */
/* -------------------------------------------------------------------------- */

/**
 * Deriva o checklist do status, exatamente como o Kanban de produção faz ao
 * arrastar um card. `extra` marca etapas opcionais (legendas, motion, cor).
 */
function checklistFor(status: VideoStatus, extra: VideoChecklistKey[] = []): VideoChecklist {
  const checklist = applyStatusToChecklist(status)
  for (const key of extra) checklist[key] = true
  return checklist
}

interface VideoSeed {
  id: string
  title: string
  clientId: string
  projectId: string
  type: VideoType
  status: VideoStatus
  priority: Priority
  deadline: string
  durationSeconds: number | null
  value: number
  estimatedHours: number
  workedHours: number
  extra?: VideoChecklistKey[]
  notes?: string
  links?: { label: string; url: string }[]
  createdOn: string
}

const videoSeeds: VideoSeed[] = [
  /* --- João Silva — Canal YouTube (p1) --- */
  {
    id: 'v1',
    title: '5 Erros que Acabam com seu Dinheiro',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.DELIVERED,
    priority: Priority.MEDIUM,
    deadline: '2026-07-07',
    durationSeconds: 742,
    value: 400,
    estimatedHours: 6,
    workedHours: 5.5,
    extra: ['soundDesign', 'colorGrading', 'subtitles'],
    links: [{ label: 'Google Drive', url: 'https://drive.google.com/drive/folders/joao-v1' }],
    createdOn: '2026-06-28',
  },
  {
    id: 'v2',
    title: 'Como Investir com R$100',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.APPROVED,
    priority: Priority.MEDIUM,
    deadline: '2026-07-14',
    durationSeconds: 688,
    value: 400,
    estimatedHours: 6,
    workedHours: 6,
    extra: ['soundDesign', 'colorGrading', 'subtitles'],
    notes: 'Aprovado pelo cliente. Falta apenas subir o master final.',
    createdOn: '2026-07-02',
  },
  {
    id: 'v3',
    title: 'Renda Extra em 2026',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.SENT_TO_CLIENT,
    priority: Priority.HIGH,
    deadline: '2026-07-21',
    durationSeconds: 815,
    value: 400,
    estimatedHours: 6,
    workedHours: 7,
    extra: ['soundDesign', 'subtitles'],
    notes: 'Segunda versão enviada. Aguardando retorno sobre o corte em 3:20.',
    links: [{ label: 'Frame.io', url: 'https://frame.io/reviews/joao-v3' }],
    createdOn: '2026-07-09',
  },
  {
    id: 'v4',
    title: 'Cartão de Crédito: Guia Completo',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.EDITING,
    priority: Priority.URGENT,
    deadline: '2026-07-28',
    durationSeconds: null,
    value: 400,
    estimatedHours: 6,
    workedHours: 3,
    createdOn: '2026-07-16',
  },
  {
    id: 'v5',
    title: 'Tesouro Direto Explicado',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.MATERIAL_RECEIVED,
    priority: Priority.HIGH,
    deadline: '2026-08-04',
    durationSeconds: null,
    value: 400,
    estimatedHours: 6,
    workedHours: 0,
    createdOn: '2026-07-23',
  },
  {
    id: 'v6',
    title: 'Como Organizar suas Finanças',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_LONGFORM,
    status: VideoStatus.BRIEFING,
    priority: Priority.MEDIUM,
    deadline: '2026-08-11',
    durationSeconds: null,
    value: 400,
    estimatedHours: 6,
    workedHours: 0,
    createdOn: '2026-07-30',
  },
  {
    id: 'v7',
    title: 'Investimentos para Iniciantes #shorts',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_SHORT,
    status: VideoStatus.DELIVERED,
    priority: Priority.LOW,
    deadline: '2026-07-10',
    durationSeconds: 48,
    value: 200,
    estimatedHours: 2,
    workedHours: 1.5,
    extra: ['subtitles'],
    createdOn: '2026-07-03',
  },
  {
    id: 'v8',
    title: 'Dica Rápida: Poupança #shorts',
    clientId: 'c1',
    projectId: 'p1',
    type: VideoType.YOUTUBE_SHORT,
    status: VideoStatus.DELIVERED,
    priority: Priority.LOW,
    deadline: '2026-07-20',
    durationSeconds: 52,
    value: 200,
    estimatedHours: 2,
    workedHours: 2,
    extra: ['subtitles'],
    createdOn: '2026-07-13',
  },

  /* --- Maria Santos — Reels Julho (p2) --- */
  {
    id: 'v9',
    title: 'Skincare Matinal',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.DELIVERED,
    priority: Priority.MEDIUM,
    deadline: '2026-07-05',
    durationSeconds: 42,
    value: 200,
    estimatedHours: 2,
    workedHours: 2,
    extra: ['subtitles', 'colorGrading'],
    createdOn: '2026-07-01',
  },
  {
    id: 'v10',
    title: 'Tutorial Maquiagem Natural',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.DELIVERED,
    priority: Priority.MEDIUM,
    deadline: '2026-07-10',
    durationSeconds: 58,
    value: 200,
    estimatedHours: 2,
    workedHours: 2.5,
    extra: ['subtitles', 'colorGrading'],
    createdOn: '2026-07-03',
  },
  {
    id: 'v11',
    title: 'Antes e Depois Tratamento',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.APPROVED,
    priority: Priority.MEDIUM,
    deadline: '2026-07-15',
    durationSeconds: 36,
    value: 200,
    estimatedHours: 2,
    workedHours: 2,
    extra: ['subtitles', 'colorGrading'],
    createdOn: '2026-07-08',
  },
  {
    id: 'v12',
    title: 'Rotina Noturna',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.CHANGES,
    priority: Priority.URGENT,
    deadline: '2026-07-20',
    durationSeconds: 51,
    value: 200,
    estimatedHours: 2,
    workedHours: 3,
    extra: ['subtitles'],
    notes: 'Cliente pediu para cortar a transição e incluir texto em overlay.',
    createdOn: '2026-07-13',
  },
  {
    id: 'v13',
    title: 'Produtos Favoritos Julho',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.EDITING,
    priority: Priority.HIGH,
    deadline: '2026-07-25',
    durationSeconds: null,
    value: 200,
    estimatedHours: 2,
    workedHours: 1,
    createdOn: '2026-07-18',
  },
  {
    id: 'v14',
    title: 'Hidratação Express',
    clientId: 'c2',
    projectId: 'p2',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.BRIEFING,
    priority: Priority.MEDIUM,
    deadline: '2026-07-30',
    durationSeconds: null,
    value: 200,
    estimatedHours: 2,
    workedHours: 0,
    createdOn: '2026-07-22',
  },

  /* --- Pedro Costa — Vídeo Institucional (p3) --- */
  {
    id: 'v15',
    title: 'Institucional TechVida',
    clientId: 'c3',
    projectId: 'p3',
    type: VideoType.INSTITUTIONAL,
    status: VideoStatus.INTERNAL_REVIEW,
    priority: Priority.URGENT,
    deadline: '2026-08-10',
    durationSeconds: 124,
    value: 4500,
    estimatedHours: 20,
    workedHours: 14,
    extra: ['soundDesign', 'motionGraphics'],
    notes: 'Motion entregue pelo freelancer. Falta conferir color grading antes de enviar.',
    links: [
      { label: 'Google Drive', url: 'https://drive.google.com/drive/folders/techvida-inst' },
      { label: 'Frame.io', url: 'https://frame.io/reviews/techvida-inst-v1' },
    ],
    createdOn: '2026-07-15',
  },

  /* --- Agência Norte — Campanha Ads (p5) --- */
  {
    id: 'v16',
    title: 'Ad Produto A — 30s',
    clientId: 'c5',
    projectId: 'p5',
    type: VideoType.AD,
    status: VideoStatus.EDITING,
    priority: Priority.URGENT,
    deadline: '2026-08-10',
    durationSeconds: 30,
    value: 1000,
    estimatedHours: 4,
    workedHours: 2,
    createdOn: '2026-08-01',
  },
  {
    id: 'v17',
    title: 'Ad Produto A — 15s',
    clientId: 'c5',
    projectId: 'p5',
    type: VideoType.AD,
    status: VideoStatus.MATERIAL_RECEIVED,
    priority: Priority.HIGH,
    deadline: '2026-08-12',
    durationSeconds: 15,
    value: 800,
    estimatedHours: 3,
    workedHours: 0,
    createdOn: '2026-08-01',
  },
  {
    id: 'v18',
    title: 'Ad Produto B — 30s',
    clientId: 'c5',
    projectId: 'p5',
    type: VideoType.AD,
    status: VideoStatus.BRIEFING,
    priority: Priority.HIGH,
    deadline: '2026-08-18',
    durationSeconds: 30,
    value: 1000,
    estimatedHours: 4,
    workedHours: 0,
    createdOn: '2026-08-04',
  },
  {
    id: 'v19',
    title: 'Ad Produto B — 15s',
    clientId: 'c5',
    projectId: 'p5',
    type: VideoType.AD,
    status: VideoStatus.BRIEFING,
    priority: Priority.MEDIUM,
    deadline: '2026-08-20',
    durationSeconds: 15,
    value: 800,
    estimatedHours: 3,
    workedHours: 0,
    createdOn: '2026-08-04',
  },
  {
    id: 'v20',
    title: 'Ad Compilação — 60s',
    clientId: 'c5',
    projectId: 'p5',
    type: VideoType.AD,
    status: VideoStatus.BRIEFING,
    priority: Priority.MEDIUM,
    deadline: '2026-08-25',
    durationSeconds: 60,
    value: 1400,
    estimatedHours: 6,
    workedHours: 0,
    createdOn: '2026-08-04',
  },

  /* --- Maria Santos — Reels Agosto (p8) --- */
  {
    id: 'v21',
    title: 'Tendências Agosto',
    clientId: 'c2',
    projectId: 'p8',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.MATERIAL_RECEIVED,
    priority: Priority.HIGH,
    deadline: '2026-08-08',
    durationSeconds: null,
    value: 200,
    estimatedHours: 2,
    workedHours: 0,
    createdOn: '2026-08-01',
  },
  {
    id: 'v22',
    title: 'Look do Dia',
    clientId: 'c2',
    projectId: 'p8',
    type: VideoType.INSTAGRAM_REEL,
    status: VideoStatus.BRIEFING,
    priority: Priority.MEDIUM,
    deadline: '2026-08-15',
    durationSeconds: null,
    value: 200,
    estimatedHours: 2,
    workedHours: 0,
    createdOn: '2026-08-01',
  },

  /* --- Pedro Costa — Podcast (p7, concluído) --- */
  {
    id: 'v23',
    title: 'Podcast Ep.1',
    clientId: 'c3',
    projectId: 'p7',
    type: VideoType.PODCAST,
    status: VideoStatus.DELIVERED,
    priority: Priority.MEDIUM,
    deadline: '2026-05-15',
    durationSeconds: 3480,
    value: 1500,
    estimatedHours: 8,
    workedHours: 9,
    extra: ['soundDesign', 'subtitles'],
    createdOn: '2026-04-20',
  },
  {
    id: 'v24',
    title: 'Podcast Ep.2',
    clientId: 'c3',
    projectId: 'p7',
    type: VideoType.PODCAST,
    status: VideoStatus.DELIVERED,
    priority: Priority.MEDIUM,
    deadline: '2026-06-15',
    durationSeconds: 3255,
    value: 1500,
    estimatedHours: 8,
    workedHours: 7,
    extra: ['soundDesign', 'subtitles'],
    createdOn: '2026-05-20',
  },
]

const videos: Video[] = videoSeeds.map((seed) => {
  const fileLinks: FileLink[] = (seed.links ?? []).map((link, index) => ({
    id: `${seed.id}_link${index + 1}`,
    videoId: seed.id,
    label: link.label,
    url: link.url,
    createdAt: at(seed.createdOn),
  }))

  return {
    id: seed.id,
    title: seed.title,
    clientId: seed.clientId,
    projectId: seed.projectId,
    type: seed.type,
    status: seed.status,
    priority: seed.priority,
    deadline: seed.deadline,
    durationSeconds: seed.durationSeconds,
    value: seed.value,
    // Os custos vivem em `expenses`, para não somar duas vezes no resultado.
    cost: 0,
    estimatedHours: seed.estimatedHours,
    workedHours: seed.workedHours,
    fileLinks,
    notes: seed.notes ?? null,
    checklist: checklistFor(seed.status, seed.extra),
    createdAt: at(seed.createdOn),
    updatedAt: at(seed.deadline),
  }
})

/* -------------------------------------------------------------------------- */
/*                                   Leads                                    */
/* -------------------------------------------------------------------------- */

interface LeadSeed {
  id: string
  name: string
  company: string | null
  niche: string
  stage: LeadStage
  potentialValue: number
  source: LeadSource
  createdOn: string
  firstContact?: string
  lastContact?: string
  nextFollowUp?: string
  followUpAction?: string
  desiredService: string
  notes?: string
}

const leadSeeds: LeadSeed[] = [
  {
    id: 'l1',
    name: 'Rafael Mendes',
    company: null,
    niche: 'Educação',
    stage: LeadStage.NEW,
    potentialValue: 2000,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-08-20',
    desiredService: 'Edição de aulas para curso online',
  },
  {
    id: 'l2',
    name: 'Carla Oliveira',
    company: 'Studio CO',
    niche: 'Moda',
    stage: LeadStage.NEW,
    potentialValue: 3000,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-08-22',
    desiredService: 'Reels mensais para lançamento de coleção',
  },
  {
    id: 'l3',
    name: 'Bruno Ferreira',
    company: 'BF Tech',
    niche: 'SaaS',
    stage: LeadStage.CONTACTED,
    potentialValue: 5000,
    source: LeadSource.COLD_EMAIL,
    createdOn: '2026-08-14',
    firstContact: '2026-08-14',
    lastContact: '2026-08-14',
    nextFollowUp: '2026-08-27',
    followUpAction: 'Reenviar e-mail com portfólio de vídeos de produto',
    desiredService: 'Vídeos de demonstração de produto',
  },
  {
    id: 'l4',
    name: 'Ana Souza',
    company: null,
    niche: 'Culinária',
    stage: LeadStage.CONTACTED,
    potentialValue: 1500,
    source: LeadSource.REFERRAL,
    createdOn: '2026-08-15',
    firstContact: '2026-08-16',
    lastContact: '2026-08-16',
    nextFollowUp: '2026-08-28',
    followUpAction: 'Ligar para entender a frequência de publicação',
    desiredService: 'Cortes de receitas para Instagram',
  },
  {
    id: 'l5',
    name: 'Thiago Lima',
    company: 'TL Invest',
    niche: 'Finanças',
    stage: LeadStage.REPLIED,
    potentialValue: 4000,
    source: LeadSource.YOUTUBE,
    createdOn: '2026-08-08',
    firstContact: '2026-08-08',
    lastContact: '2026-08-21',
    nextFollowUp: '2026-08-26',
    followUpAction: 'Enviar orçamento de 4 vídeos mensais',
    desiredService: 'Canal semanal de finanças',
    notes: 'Já produz sozinho. Busca ganhar tempo terceirizando a edição.',
  },
  {
    id: 'l6',
    name: 'Fernanda Reis',
    company: null,
    niche: 'Saúde',
    stage: LeadStage.REPLIED,
    potentialValue: 2500,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-08-11',
    firstContact: '2026-08-11',
    lastContact: '2026-08-22',
    nextFollowUp: '2026-08-29',
    followUpAction: 'Enviar cases de vídeos na área de saúde',
    desiredService: 'Reels educativos semanais',
  },
  {
    id: 'l7',
    name: 'Ricardo Martins',
    company: 'RM Agency',
    niche: 'Marketing',
    stage: LeadStage.MEETING,
    potentialValue: 8000,
    source: LeadSource.NETWORKING,
    createdOn: '2026-08-03',
    firstContact: '2026-08-03',
    lastContact: '2026-08-24',
    nextFollowUp: '2026-08-26',
    followUpAction: 'Reunião de alinhamento de escopo às 15h',
    desiredService: 'Parceria fixa de edição para clientes da agência',
    notes: 'Maior oportunidade do funil. Volume recorrente se fechar.',
  },
  {
    id: 'l8',
    name: 'Juliana Campos',
    company: null,
    niche: 'Lifestyle',
    stage: LeadStage.MEETING,
    potentialValue: 3000,
    source: LeadSource.REFERRAL,
    createdOn: '2026-08-06',
    firstContact: '2026-08-07',
    lastContact: '2026-08-23',
    nextFollowUp: '2026-08-30',
    followUpAction: 'Confirmar reunião e enviar pauta',
    desiredService: 'Vlogs semanais editados',
  },
  {
    id: 'l9',
    name: 'Diego Santos',
    company: 'DS Fit',
    niche: 'Fitness',
    stage: LeadStage.PROPOSAL_SENT,
    potentialValue: 2400,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-07-29',
    firstContact: '2026-07-29',
    lastContact: '2026-08-19',
    nextFollowUp: '2026-08-27',
    followUpAction: 'Cobrar retorno da proposta enviada dia 19',
    desiredService: 'Pacote mensal de 6 reels',
  },
  {
    id: 'l10',
    name: 'Patrícia Alves',
    company: null,
    niche: 'Educação',
    stage: LeadStage.PROPOSAL_SENT,
    potentialValue: 3500,
    source: LeadSource.WEBSITE,
    createdOn: '2026-08-02',
    firstContact: '2026-08-02',
    lastContact: '2026-08-20',
    nextFollowUp: '2026-08-28',
    followUpAction: 'Follow-up da proposta por WhatsApp',
    desiredService: 'Edição de módulos de curso',
  },
  {
    id: 'l11',
    name: 'Marcos Vieira',
    company: 'MV Prod',
    niche: 'Entretenimento',
    stage: LeadStage.NEGOTIATION,
    potentialValue: 6000,
    source: LeadSource.YOUTUBE,
    createdOn: '2026-07-18',
    firstContact: '2026-07-18',
    lastContact: '2026-08-24',
    nextFollowUp: '2026-08-26',
    followUpAction: 'Fechar condição de pagamento em duas parcelas',
    desiredService: 'Série de 10 vídeos para canal',
    notes: 'Negociando prazo de pagamento. Escopo já acordado.',
  },
  {
    id: 'l12',
    name: 'Camila Costa',
    company: null,
    niche: 'Gastronomia',
    stage: LeadStage.NEGOTIATION,
    potentialValue: 2000,
    source: LeadSource.REFERRAL,
    createdOn: '2026-07-24',
    firstContact: '2026-07-24',
    lastContact: '2026-08-22',
    nextFollowUp: '2026-08-29',
    followUpAction: 'Ajustar escopo para caber no orçamento',
    desiredService: 'Reels de receitas quinzenais',
  },
  {
    id: 'l13',
    name: 'Felipe Rocha',
    company: 'FR Digital',
    niche: 'E-commerce',
    stage: LeadStage.CLOSED,
    potentialValue: 4500,
    source: LeadSource.COLD_EMAIL,
    createdOn: '2026-06-12',
    firstContact: '2026-06-12',
    lastContact: '2026-07-30',
    desiredService: 'Vídeos de produto para catálogo',
    notes: 'Fechado. Converter em cliente para abrir o primeiro projeto.',
  },
  {
    id: 'l14',
    name: 'Isabela Nunes',
    company: null,
    niche: 'Beleza',
    stage: LeadStage.CLOSED,
    potentialValue: 2800,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-06-30',
    firstContact: '2026-06-30',
    lastContact: '2026-08-12',
    desiredService: 'Pacote mensal de reels',
    notes: 'Fechado. Aguardando conversão em cliente.',
  },
  {
    id: 'l15',
    name: 'André Lopes',
    company: null,
    niche: 'Tecnologia',
    stage: LeadStage.LOST,
    potentialValue: 3000,
    source: LeadSource.WEBSITE,
    createdOn: '2026-06-18',
    firstContact: '2026-06-18',
    lastContact: '2026-07-14',
    desiredService: 'Vídeos técnicos',
    notes: 'Optou por contratar editor interno.',
  },
  {
    id: 'l16',
    name: 'Renata Dias',
    company: null,
    niche: 'Fitness',
    stage: LeadStage.LOST,
    potentialValue: 1800,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-07-02',
    firstContact: '2026-07-03',
    lastContact: '2026-07-28',
    desiredService: 'Reels de treino',
    notes: 'Orçamento acima do que podia pagar.',
  },
  {
    id: 'l17',
    name: 'Gustavo Pinto',
    company: 'GP Studio',
    niche: 'Música',
    stage: LeadStage.NEW,
    potentialValue: 2200,
    source: LeadSource.REFERRAL,
    createdOn: '2026-08-24',
    desiredService: 'Videoclipes e bastidores',
  },
  {
    id: 'l18',
    name: 'Larissa Moura',
    company: null,
    niche: 'Viagem',
    stage: LeadStage.CONTACTED,
    potentialValue: 1500,
    source: LeadSource.INSTAGRAM,
    createdOn: '2026-08-17',
    firstContact: '2026-08-18',
    lastContact: '2026-08-18',
    nextFollowUp: '2026-08-30',
    followUpAction: 'Enviar mensagem com exemplos de vlogs de viagem',
    desiredService: 'Edição de vlogs de viagem',
  },
]

/** Gera e-mail e handle a partir do nome, só para o cenário parecer completo. */
function contactHandles(name: string): { email: string; instagram: string } {
  const slug = name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[^a-z ]/g, '')
    .trim()
    .split(/\s+/)
    .join('.')
  return { email: `${slug}@email.com`, instagram: `@${slug.replace(/\./g, '')}` }
}

const leads: Lead[] = leadSeeds.map((seed) => {
  const { email, instagram } = contactHandles(seed.name)
  return {
    id: seed.id,
    name: seed.name,
    company: seed.company,
    email,
    phone: null,
    whatsapp: null,
    instagram,
    youtube: null,
    website: seed.company ? `${seed.company.toLowerCase().replace(/\s+/g, '')}.com.br` : null,
    niche: seed.niche,
    source: seed.source,
    desiredService: seed.desiredService,
    estimatedBudget: seed.potentialValue,
    potentialValue: seed.potentialValue,
    stage: seed.stage,
    closeProbability: LEAD_STAGE_PROBABILITY[seed.stage],
    firstContactDate: seed.firstContact ?? null,
    lastContactDate: seed.lastContact ?? null,
    nextFollowUpDate: seed.nextFollowUp ?? null,
    nextFollowUpAction: seed.followUpAction ?? null,
    notes: seed.notes ?? null,
    convertedToClientId: null,
    convertedAt: null,
    createdAt: at(seed.createdOn),
    updatedAt: at(seed.lastContact ?? seed.createdOn),
  }
})

/* -------------------------------------------------------------------------- */
/*                          Atividades dos leads                              */
/* -------------------------------------------------------------------------- */

/** O que registrar quando um lead alcança cada etapa. */
const STAGE_ACTIVITY: Record<LeadStage, { type: LeadActivity['type']; title: string }> = {
  [LeadStage.NEW]: { type: 'note', title: 'Lead cadastrado' },
  [LeadStage.CONTACTED]: { type: 'contact', title: 'Primeiro contato enviado' },
  [LeadStage.REPLIED]: { type: 'message', title: 'Lead respondeu' },
  [LeadStage.MEETING]: { type: 'meeting', title: 'Reunião agendada' },
  [LeadStage.PROPOSAL_SENT]: { type: 'proposal', title: 'Proposta enviada' },
  [LeadStage.NEGOTIATION]: { type: 'message', title: 'Negociação iniciada' },
  [LeadStage.CLOSED]: { type: 'stage_change', title: 'Negócio fechado' },
  [LeadStage.LOST]: { type: 'stage_change', title: 'Oportunidade perdida' },
}

/**
 * Reconstrói o histórico de cada lead a partir da etapa em que ele está:
 * uma entrada por etapa percorrida, distribuída entre o cadastro e o último
 * contato registrado.
 */
const leadActivities: LeadActivity[] = leads.flatMap((lead) => {
  const reached = LEAD_STAGE_ORDER.slice(0, LEAD_STAGE_ORDER.indexOf(lead.stage) + 1)
  const start = new Date(`${lead.createdAt}`).getTime()
  const end = new Date(`${lead.updatedAt}`).getTime()
  const span = Math.max(end - start, 0)

  return reached.map((stage, index) => {
    const template = STAGE_ACTIVITY[stage]
    const ratio = reached.length > 1 ? index / (reached.length - 1) : 0
    const date = new Date(start + span * ratio).toISOString()
    return {
      id: `${lead.id}_act${index + 1}`,
      leadId: lead.id,
      type: template.type,
      title: template.title,
      description: index === 0 ? lead.desiredService : null,
      date: date.slice(0, 10),
      createdAt: date,
    }
  })
})

/* -------------------------------------------------------------------------- */
/*                                 Pagamentos                                 */
/* -------------------------------------------------------------------------- */

const payments: Payment[] = [
  {
    id: 'pay1',
    description: 'YouTube Jul — parcela 1',
    amount: 1600,
    clientId: 'c1',
    projectId: 'p1',
    videoId: null,
    dueDate: '2026-07-15',
    paymentDate: '2026-07-15',
    status: PaymentStatus.PAID,
    method: PaymentMethod.PIX,
    notes: null,
    createdAt: at('2026-07-01'),
    updatedAt: at('2026-07-15'),
  },
  {
    id: 'pay2',
    description: 'YouTube Jul — parcela 2',
    amount: 1600,
    clientId: 'c1',
    projectId: 'p1',
    videoId: null,
    dueDate: '2026-07-31',
    paymentDate: null,
    status: PaymentStatus.PENDING,
    method: null,
    notes: null,
    createdAt: at('2026-07-01'),
    updatedAt: at('2026-07-01'),
  },
  {
    id: 'pay3',
    description: 'Reels Jul',
    amount: 2400,
    clientId: 'c2',
    projectId: 'p2',
    videoId: null,
    dueDate: '2026-07-31',
    paymentDate: '2026-07-30',
    status: PaymentStatus.PAID,
    method: PaymentMethod.PIX,
    notes: null,
    createdAt: at('2026-07-01'),
    updatedAt: at('2026-07-30'),
  },
  {
    id: 'pay4',
    description: 'Institucional — entrada',
    amount: 2250,
    clientId: 'c3',
    projectId: 'p3',
    videoId: null,
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    status: PaymentStatus.PAID,
    method: PaymentMethod.BANK_TRANSFER,
    notes: '50% na assinatura.',
    createdAt: at('2026-07-15'),
    updatedAt: at('2026-07-20'),
  },
  {
    id: 'pay5',
    description: 'Institucional — final',
    amount: 2250,
    clientId: 'c3',
    projectId: 'p3',
    videoId: null,
    dueDate: '2026-08-15',
    paymentDate: null,
    status: PaymentStatus.PENDING,
    method: null,
    notes: '50% na entrega.',
    createdAt: at('2026-07-15'),
    updatedAt: at('2026-07-15'),
  },
  {
    id: 'pay6',
    description: 'Campanha Ads — parcela 1',
    amount: 3000,
    clientId: 'c5',
    projectId: 'p5',
    videoId: null,
    dueDate: '2026-08-10',
    paymentDate: null,
    status: PaymentStatus.PENDING,
    method: null,
    notes: null,
    createdAt: at('2026-08-01'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'pay7',
    description: 'Campanha Ads — parcela 2',
    amount: 3000,
    clientId: 'c5',
    projectId: 'p5',
    videoId: null,
    dueDate: '2026-08-31',
    paymentDate: null,
    status: PaymentStatus.PENDING,
    method: null,
    notes: null,
    createdAt: at('2026-08-01'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'pay8',
    description: 'Reels Ago',
    amount: 2400,
    clientId: 'c2',
    projectId: 'p8',
    videoId: null,
    dueDate: '2026-08-31',
    paymentDate: null,
    status: PaymentStatus.PENDING,
    method: null,
    notes: null,
    createdAt: at('2026-08-01'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'pay9',
    description: 'Reels Fitness Mai',
    amount: 1600,
    clientId: 'c4',
    projectId: 'p4',
    videoId: null,
    dueDate: '2026-05-31',
    paymentDate: null,
    status: PaymentStatus.OVERDUE,
    method: null,
    notes: 'Cobrança enviada duas vezes. Sem retorno.',
    createdAt: at('2026-05-01'),
    updatedAt: at('2026-06-10'),
  },
  {
    id: 'pay10',
    description: 'Podcast Ep.1',
    amount: 1500,
    clientId: 'c3',
    projectId: 'p7',
    videoId: 'v23',
    dueDate: '2026-05-20',
    paymentDate: '2026-05-20',
    status: PaymentStatus.PAID,
    method: PaymentMethod.PIX,
    notes: null,
    createdAt: at('2026-05-01'),
    updatedAt: at('2026-05-20'),
  },
  {
    id: 'pay11',
    description: 'Podcast Ep.2',
    amount: 1500,
    clientId: 'c3',
    projectId: 'p7',
    videoId: 'v24',
    dueDate: '2026-06-20',
    paymentDate: '2026-06-18',
    status: PaymentStatus.PAID,
    method: PaymentMethod.PIX,
    notes: null,
    createdAt: at('2026-06-01'),
    updatedAt: at('2026-06-18'),
  },
]

/* -------------------------------------------------------------------------- */
/*                                   Custos                                   */
/* -------------------------------------------------------------------------- */

const expenses: Expense[] = [
  {
    id: 'exp1',
    description: 'Banco de música — Artlist',
    amount: 150,
    category: ExpenseCategory.MUSIC,
    clientId: null,
    projectId: null,
    videoId: null,
    date: '2026-07-01',
    notes: 'Assinatura mensal.',
    createdAt: at('2026-07-01'),
    updatedAt: at('2026-07-01'),
  },
  {
    id: 'exp2',
    description: 'Adobe Creative Cloud',
    amount: 290,
    category: ExpenseCategory.SOFTWARE,
    clientId: null,
    projectId: null,
    videoId: null,
    date: '2026-07-05',
    notes: 'Assinatura mensal.',
    createdAt: at('2026-07-05'),
    updatedAt: at('2026-07-05'),
  },
  {
    id: 'exp3',
    description: 'Freelancer — motion graphics',
    amount: 400,
    category: ExpenseCategory.FREELANCER,
    clientId: 'c3',
    projectId: 'p3',
    videoId: null,
    date: '2026-08-01',
    notes: null,
    createdAt: at('2026-08-01'),
    updatedAt: at('2026-08-01'),
  },
  {
    id: 'exp4',
    description: 'Stock footage — institucional',
    amount: 180,
    category: ExpenseCategory.STOCK,
    clientId: 'c3',
    projectId: 'p3',
    videoId: null,
    date: '2026-07-25',
    notes: null,
    createdAt: at('2026-07-25'),
    updatedAt: at('2026-07-25'),
  },
  {
    id: 'exp5',
    description: 'Freelancer — legendas',
    amount: 120,
    category: ExpenseCategory.FREELANCER,
    clientId: 'c1',
    projectId: 'p1',
    videoId: null,
    date: '2026-07-10',
    notes: null,
    createdAt: at('2026-07-10'),
    updatedAt: at('2026-07-10'),
  },
  {
    id: 'exp6',
    description: 'Plugin — Reel transitions',
    amount: 80,
    category: ExpenseCategory.PLUGINS,
    clientId: 'c2',
    projectId: 'p2',
    videoId: null,
    date: '2026-07-03',
    notes: null,
    createdAt: at('2026-07-03'),
    updatedAt: at('2026-07-03'),
  },
  {
    id: 'exp7',
    description: 'Stock music — ads',
    amount: 200,
    category: ExpenseCategory.MUSIC,
    clientId: 'c5',
    projectId: 'p5',
    videoId: null,
    date: '2026-08-05',
    notes: null,
    createdAt: at('2026-08-05'),
    updatedAt: at('2026-08-05'),
  },
  {
    id: 'exp8',
    description: 'Adobe Creative Cloud',
    amount: 290,
    category: ExpenseCategory.SOFTWARE,
    clientId: null,
    projectId: null,
    videoId: null,
    date: '2026-08-05',
    notes: 'Assinatura mensal.',
    createdAt: at('2026-08-05'),
    updatedAt: at('2026-08-05'),
  },
  {
    id: 'exp9',
    description: 'Banco de música — Artlist',
    amount: 150,
    category: ExpenseCategory.MUSIC,
    clientId: null,
    projectId: null,
    videoId: null,
    date: '2026-08-01',
    notes: 'Assinatura mensal.',
    createdAt: at('2026-08-01'),
    updatedAt: at('2026-08-01'),
  },
]

/* -------------------------------------------------------------------------- */
/*                                 Contratos                                  */
/* -------------------------------------------------------------------------- */

const contracts: Contract[] = [
  {
    id: 'ct1',
    clientId: 'c1',
    value: 3200,
    frequency: ContractFrequency.MONTHLY,
    startDate: '2026-01-01',
    renewalDate: '2026-09-01',
    videoQuantity: 8,
    status: ContractStatus.ACTIVE,
    notes: '6 longform + 2 shorts por mês.',
    createdAt: at('2026-01-01'),
    updatedAt: at('2026-01-01'),
  },
  {
    id: 'ct2',
    clientId: 'c2',
    value: 2400,
    frequency: ContractFrequency.MONTHLY,
    startDate: '2026-03-01',
    renewalDate: '2026-09-01',
    videoQuantity: 6,
    status: ContractStatus.ACTIVE,
    notes: '6 reels por mês.',
    createdAt: at('2026-03-01'),
    updatedAt: at('2026-03-01'),
  },
  {
    id: 'ct3',
    clientId: 'c3',
    value: 3000,
    frequency: ContractFrequency.ONE_TIME,
    startDate: '2026-04-01',
    renewalDate: null,
    videoQuantity: 2,
    status: ContractStatus.ACTIVE,
    notes: 'Série de podcast, escopo fechado.',
    createdAt: at('2026-04-01'),
    updatedAt: at('2026-04-01'),
  },
]

/* -------------------------------------------------------------------------- */
/*                                  Tarefas                                   */
/* -------------------------------------------------------------------------- */

const tasks: Task[] = [
  {
    id: 't1',
    title: 'Organizar assets João',
    description: 'Renomear e organizar as pastas do material bruto.',
    responsible: 'Gabriel',
    priority: Priority.MEDIUM,
    status: TaskStatus.DONE,
    deadline: '2026-07-06',
    clientId: 'c1',
    projectId: 'p1',
    videoId: null,
    createdAt: at('2026-07-01'),
    updatedAt: at('2026-07-06'),
  },
  {
    id: 't2',
    title: 'Enviar v3 para revisão',
    description: 'Subir a versão 2 no Frame.io e avisar o cliente.',
    responsible: 'Gabriel',
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    deadline: '2026-08-26',
    clientId: 'c1',
    projectId: 'p1',
    videoId: 'v3',
    createdAt: at('2026-08-20'),
    updatedAt: at('2026-08-20'),
  },
  {
    id: 't3',
    title: 'Comprar stock footage ads',
    description: 'Selecionar 4 clipes para a campanha da Agência Norte.',
    responsible: 'Gabriel',
    priority: Priority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    deadline: '2026-08-08',
    clientId: 'c5',
    projectId: 'p5',
    videoId: 'v16',
    createdAt: at('2026-08-02'),
    updatedAt: at('2026-08-06'),
  },
  {
    id: 't4',
    title: 'Briefing Produto B com cliente',
    description: 'Alinhar mensagem e call to action das peças do Produto B.',
    responsible: 'Gabriel',
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    deadline: '2026-08-12',
    clientId: 'c5',
    projectId: 'p5',
    videoId: 'v18',
    createdAt: at('2026-08-04'),
    updatedAt: at('2026-08-04'),
  },
  {
    id: 't5',
    title: 'Exportar versão final v2',
    description: 'Master em 4K e versão comprimida para upload.',
    responsible: 'Gabriel',
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    deadline: '2026-08-27',
    clientId: 'c1',
    projectId: 'p1',
    videoId: 'v2',
    createdAt: at('2026-08-18'),
    updatedAt: at('2026-08-18'),
  },
  {
    id: 't6',
    title: 'Cobrar Lucas Almeida',
    description: 'Fatura de maio em aberto há mais de 80 dias.',
    responsible: 'Gabriel',
    priority: Priority.URGENT,
    status: TaskStatus.TODO,
    deadline: '2026-08-26',
    clientId: 'c4',
    projectId: 'p4',
    videoId: null,
    createdAt: at('2026-08-19'),
    updatedAt: at('2026-08-19'),
  },
  {
    id: 't7',
    title: 'Aplicar alterações v12',
    description: 'Cortar transição e adicionar texto em overlay.',
    responsible: 'Gabriel',
    priority: Priority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    deadline: '2026-08-26',
    clientId: 'c2',
    projectId: 'p2',
    videoId: 'v12',
    createdAt: at('2026-08-22'),
    updatedAt: at('2026-08-25'),
  },
  {
    id: 't8',
    title: 'Revisar color grading institucional',
    description: 'Conferir consistência entre as cenas internas e externas.',
    responsible: 'Gabriel',
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    deadline: '2026-08-09',
    clientId: 'c3',
    projectId: 'p3',
    videoId: 'v15',
    createdAt: at('2026-08-05'),
    updatedAt: at('2026-08-05'),
  },
  {
    id: 't9',
    title: 'Preparar material de briefing',
    description: 'Montar roteiro base para o reel Look do Dia.',
    responsible: 'Gabriel',
    priority: Priority.LOW,
    status: TaskStatus.TODO,
    deadline: '2026-08-20',
    clientId: 'c2',
    projectId: 'p8',
    videoId: 'v22',
    createdAt: at('2026-08-10'),
    updatedAt: at('2026-08-10'),
  },
  {
    id: 't10',
    title: 'Renovar contrato João',
    description: 'Contrato vence em 01/09. Propor reajuste de 10%.',
    responsible: 'Gabriel',
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    deadline: '2026-08-25',
    clientId: 'c1',
    projectId: null,
    videoId: null,
    createdAt: at('2026-08-15'),
    updatedAt: at('2026-08-15'),
  },
]

/* -------------------------------------------------------------------------- */
/*                              Revisões de vídeo                             */
/* -------------------------------------------------------------------------- */

const videoRevisions: VideoRevision[] = [
  {
    id: 'rev1',
    videoId: 'v1',
    version: 1,
    date: '2026-07-04',
    comments: 'Ajustar ritmo da intro',
    changesRequested: 'Cortar 8 segundos antes da vinheta.',
    status: RevisionStatus.COMPLETED,
    createdAt: at('2026-07-04'),
  },
  {
    id: 'rev2',
    videoId: 'v1',
    version: 2,
    date: '2026-07-06',
    comments: 'Aprovado',
    changesRequested: null,
    status: RevisionStatus.COMPLETED,
    createdAt: at('2026-07-06'),
  },
  {
    id: 'rev3',
    videoId: 'v3',
    version: 1,
    date: '2026-07-19',
    comments: 'Trocar música do meio, cortar 15s no final',
    changesRequested: 'Substituir trilha a partir de 4:10 e encurtar o encerramento.',
    status: RevisionStatus.COMPLETED,
    createdAt: at('2026-07-19'),
  },
  {
    id: 'rev4',
    videoId: 'v3',
    version: 2,
    date: '2026-07-20',
    comments: 'Ajustar corte no minuto 3:20',
    changesRequested: 'Suavizar o corte seco entre as duas falas.',
    status: RevisionStatus.IN_PROGRESS,
    createdAt: at('2026-07-20'),
  },
  {
    id: 'rev5',
    videoId: 'v12',
    version: 1,
    date: '2026-07-22',
    comments: 'Cortar transição, adicionar texto overlay',
    changesRequested: 'Remover a transição de zoom e inserir o nome dos produtos.',
    status: RevisionStatus.IN_PROGRESS,
    createdAt: at('2026-07-22'),
  },
  {
    id: 'rev6',
    videoId: 'v15',
    version: 1,
    date: '2026-08-05',
    comments: 'Versão inicial para revisão interna',
    changesRequested: 'Conferir color grading e mixagem antes de enviar ao cliente.',
    status: RevisionStatus.IN_PROGRESS,
    createdAt: at('2026-08-05'),
  },
]

/* -------------------------------------------------------------------------- */
/*                            Calendário e histórico                          */
/* -------------------------------------------------------------------------- */

/**
 * Só entram aqui os compromissos que não dão para derivar de outra entidade.
 * Prazos, pagamentos e follow-ups o calendário monta a partir dos próprios
 * registros — duplicá-los aqui criaria duas fontes de verdade.
 */
const calendarEvents: CalendarEvent[] = [
  {
    id: 'ev1',
    title: 'Reunião de escopo — RM Agency',
    type: CalendarEventType.MEETING,
    date: '2026-08-26',
    entityType: 'lead',
    entityId: 'l7',
    notes: 'Às 15h, videochamada. Levar proposta de parceria fixa.',
    createdAt: at('2026-08-24'),
  },
  {
    id: 'ev2',
    title: 'Call de alinhamento — Juliana Campos',
    type: CalendarEventType.MEETING,
    date: '2026-08-30',
    entityType: 'lead',
    entityId: 'l8',
    notes: 'Confirmar horário na véspera.',
    createdAt: at('2026-08-23'),
  },
  {
    id: 'ev3',
    title: 'Gravação externa — TechVida',
    type: CalendarEventType.MEETING,
    date: '2026-09-02',
    entityType: 'client',
    entityId: 'c3',
    notes: 'Captação de imagens complementares para o institucional.',
    createdAt: at('2026-08-20'),
  },
]

const activityLog: ActivityLog[] = [
  {
    id: 'log1',
    action: ActivityAction.STATUS_CHANGED,
    entityType: 'video',
    entityId: 'v15',
    entityName: 'Institucional TechVida',
    details: 'Motion graphics concluído, vídeo movido para revisão interna.',
    previousValue: VideoStatus.EDITING,
    newValue: VideoStatus.INTERNAL_REVIEW,
    createdAt: at('2026-08-05', 14),
  },
  {
    id: 'log2',
    action: ActivityAction.CREATED,
    entityType: 'expense',
    entityId: 'exp3',
    entityName: 'Freelancer — motion graphics',
    details: 'Custo de R$ 400,00 vinculado ao projeto Vídeo Institucional.',
    previousValue: null,
    newValue: null,
    createdAt: at('2026-08-01', 10),
  },
  {
    id: 'log3',
    action: ActivityAction.STATUS_CHANGED,
    entityType: 'video',
    entityId: 'v12',
    entityName: 'Rotina Noturna',
    details: 'Cliente solicitou alterações na versão 1.',
    previousValue: VideoStatus.SENT_TO_CLIENT,
    newValue: VideoStatus.CHANGES,
    createdAt: at('2026-07-22', 16),
  },
  {
    id: 'log4',
    action: ActivityAction.PAYMENT_REGISTERED,
    entityType: 'payment',
    entityId: 'pay3',
    entityName: 'Reels Jul',
    details: 'R$ 2.400,00 recebidos via Pix.',
    previousValue: PaymentStatus.PENDING,
    newValue: PaymentStatus.PAID,
    createdAt: at('2026-07-30', 11),
  },
  {
    id: 'log5',
    action: ActivityAction.VIDEO_DELIVERED,
    entityType: 'video',
    entityId: 'v8',
    entityName: 'Dica Rápida: Poupança #shorts',
    details: 'Entregue dentro do prazo.',
    previousValue: VideoStatus.APPROVED,
    newValue: VideoStatus.DELIVERED,
    createdAt: at('2026-07-20', 17),
  },
  {
    id: 'log6',
    action: ActivityAction.CREATED,
    entityType: 'project',
    entityId: 'p5',
    entityName: 'Campanha Ads',
    details: '5 peças contratadas pela Agência Norte.',
    previousValue: null,
    newValue: null,
    createdAt: at('2026-07-28', 9),
  },
]

/* -------------------------------------------------------------------------- */
/*                                  Montagem                                  */
/* -------------------------------------------------------------------------- */

/**
 * Monta um banco novo com os dados demonstrativos.
 * Retorna cópias profundas para que o store possa mutar livremente sem
 * contaminar estes literais entre recarregamentos do seed.
 */
export function buildSeedDatabase(): Database {
  return structuredClone({
    leads,
    leadActivities,
    clients,
    projects,
    videos,
    videoRevisions,
    tasks,
    payments,
    expenses,
    contracts,
    calendarEvents,
    activityLog,
    notifications: [],
    meta: {
      version: SCHEMA_VERSION,
      seededAt: at(TODAY),
      updatedAt: at(TODAY),
    },
  })
}
